<a href="https://colab.research.google.com/github/9-coding/Machine_Learning/blob/main/Item_based_collaborate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  import pandas as pd
  import numpy as np
  from sklearn.neighbors import NearestNeighbors


  df = pd.DataFrame([[ 9, 2, 5, 0],
                    [ 6,10, 9,10],
                    [ 8, 6, 0, 7],
                    [ 4, 0,10, 8],
                    [ 0, 8, 7, 0]],
                    columns=['user_0', 'user_1', 'user_2', 'user_3'],
                    index=['movie_0', 'movie_1', 'movie_2', 'movie_3','movie_4'])


  print(df)


  def item_based_collaborative(movie):
    print("\n----------------------------------\n ")
    knn = NearestNeighbors(metric='cosine', algorithm='brute')
    knn.fit(df.values)
    distances, indices = knn.kneighbors(df.values, n_neighbors=3)


    print("indices\n", indices)
    print("\ndistances\n", distances)

    arr = np.ones(15)

    print()


    # get the index for 'movie'
    index_for_movie = df.index.tolist().index(movie)
    # find the indices for the similar movies
    sim_movies = indices[index_for_movie].tolist()
    # distances between 'movie' and the similar movies
    movie_distances = distances[index_for_movie].tolist()
    # the position of 'movie' in the list sim_movies
    id_movie = sim_movies.index(index_for_movie)
    # remove 'movie' from the list sim_movies
    sim_movies.remove(index_for_movie)
    # remove 'movie' from the list movie_distances
    movie_distances.pop(id_movie)

    sim_movies.sort(reverse=True)
    # movie_distances.sort(reverse=True)

    print('\nThe Nearest Movies to ', movie, sim_movies)

    print('The Distance from ', movie, ':', movie_distances)

    s1 = 1 - movie_distances[1]
    s2 = 1 - movie_distances[0]


    d1 = df.iloc[(sim_movies[1], sim_movies[0])]
    d2 = df.iloc[(sim_movies[0], sim_movies[0])]

    print("R:", (s1*d1+s2*d2)/(s1+s2))


  item_based_collaborative('movie_0')
  item_based_collaborative('movie_4')


         user_0  user_1  user_2  user_3
movie_0       9       2       5       0
movie_1       6      10       9      10
movie_2       8       6       0       7
movie_3       4       0      10       8
movie_4       0       8       7       0

----------------------------------
 
indices
 [[0 2 1]
 [1 2 3]
 [2 1 0]
 [3 1 0]
 [4 1 3]]

distances
 [[0.00000000e+00 3.43870130e-01 3.62733649e-01]
 [2.22044605e-16 1.80974852e-01 1.87850752e-01]
 [0.00000000e+00 1.80974852e-01 3.43870130e-01]
 [0.00000000e+00 1.87850752e-01 3.88824613e-01]
 [1.11022302e-16 2.44443085e-01 5.09179644e-01]]


The Nearest Movies to  movie_0 [2, 1]
The Distance from  movie_0 : [0.3438701299701922, 0.362733648590818]
R: 4.434369814612281

----------------------------------
 
indices
 [[0 2 1]
 [1 2 3]
 [2 1 0]
 [3 1 0]
 [4 1 3]]

distances
 [[0.00000000e+00 3.43870130e-01 3.62733649e-01]
 [2.22044605e-16 1.80974852e-01 1.87850752e-01]
 [0.00000000e+00 1.80974852e-01 3.43870130e-01]
 [0.00000000e+00 1.87850752e-01 3.8

In [ ]:
df = pd.DataFrame([
    [0,0,3,4,2,1,2,0,5,1],
    [3,0,1,3,0,0,0,0,0,0],
    [0,3,0,4,0,2,0,0,0,2],
    [5,2,3,2,0,4,3,3,0,0],
    [0,5,5,0,0,0,0,0,5,4],
    [0,0,0,0,4,0,4,2,3,0],
    [4,4,0,0,4,4,3,4,0,4],
    [5,0,4,2,3,0,3,3,3,3],
    [0,3,0,0,5,5,0,4,0,0],
    [2,0,0,0,0,0,0,0,4,0]],
    columns=['user_0', 'user_1', 'user_2', 'user_3', 'user_4', 'user_5', 'user_6', 'user_7','user_8','user_9',],
    index=['movie_0', 'movie_1', 'movie_2', 'movie_3','movie_4', 'movie_5', 'movie_6', 'movie_7', 'movie_8', 'movie_9'])
